name: Promote Python Package

on:
  repository_dispatch:
    types: [cloudsmith-package-synchronized]
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version to promote (e.g., 0.0.1)'
        required: true
        type: string

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_NAME: 'example_package'

permissions:
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Get package identifier and promote
        run: |
          # Query for the package and get its identifier
          PACKAGE_QUERY="filename:${PACKAGE_NAME}-${{ github.event.client_payload.package_version }}.tar.gz"
          echo "Searching for package with query: $PACKAGE_QUERY"
          
          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -q "$PACKAGE_QUERY" -F json)
          
          # Extract the identifier_perm using jq
          IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')
          
          if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" = "null" ]; then
            echo "Failed to find package identifier"
            exit 1
          fi
          
          echo "Found package identifier: $IDENTIFIER"
          cloudsmith tag add ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER ready-for-production

          # Retrieve all packages with the 'ready-for-production' tag
          PACKAGE_DATA_PRODUCTION_READY=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -q "tag:ready-for-production" -F json)
          
          # Extract the identifier_perm for ready-for-production tag packages
          IDENTIFIER_PRODUCTION_READY=$(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm')
          
          if [ -z "$IDENTIFIER_PRODUCTION_READY" ] || [ "$IDENTIFIER_PRODUCTION_READY" = "null" ]; then
            echo "Failed to find package identifier"
            exit 1
          fi
          
          echo "Found package identifier: $IDENTIFIER_PRODUCTION_READY"
          
          # Promote package using the identifier
          cloudsmith mv --yes \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER_PRODUCTION_READY \
            ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
        shell: bash
